<a href="https://colab.research.google.com/github/Pedrohsm2/Projeto-Prog-1/blob/master/atividade_pratica_aula4_kpis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade Prática — Aula 4: Análise de Dados e Construção de Indicadores (KPIs)

Esta atividade foi construída com base na Aula 4, que marca a transição **do dado limpo para a tomada de decisão estratégica**, com foco em **KPIs, métricas derivadas, dimensões de análise, rankings e insights executivos**. fileciteturn5file0

## Ideia central da aula
Antes do código, vem a **pergunta de negócio**.  
Depois, definimos:
1. a **métrica**
2. a **dimensão**
3. a **agregação**
4. e só então construímos a resposta em tabela e em texto. fileciteturn5file0

## Regras da atividade
- O notebook **orienta**, mas você deve **escrever os códigos**.
- Sempre que gerar uma tabela agregada, escreva **1 ou 2 frases interpretando o resultado**.
- O objetivo não é apenas calcular números, mas comunicar decisões.

## Dataset da atividade
Arquivo: `vendas_brasil_aula4_kpis.csv`

## 1. Preparação do ambiente

Importe as bibliotecas necessárias para a atividade.

**Sugestão:**  
- `pandas`
- `numpy`

Se desejar, você também pode usar uma biblioteca de visualização mais adiante, mas o foco desta aula é **tabela agregada + insight**.

In [1]:
import pandas as pd
import numpy as np

## 2. Leitura da base

Leia o arquivo `vendas_brasil_aula4_kpis.csv` em um DataFrame chamado `df`.

Depois:
1. exiba as primeiras linhas
2. veja o tamanho da base
3. inspecione os tipos das colunas
4. confirme se `data_venda` está pronta para análises temporais

In [2]:
df = pd.read_csv('vendas_brasil_aula4_kpis.csv')

In [3]:
df.head()

,pedido_id,data_venda,uf,canal_venda,categoria,produto,quantidade_pedidos,preco_unitario,receita,lucro
0,5000,2025-02-14,RJ,Marketplace,Periféricos,Mouse Gamer,2,237.65,475.30,239.08
1,5001,2025-02-17,PR,Online,Informática,Monitor 27,4,1431.79,5727.16,1769.48
2,5002,2025-07-22,RJ,Marketplace,Informática,Monitor 27,5,1446.22,7231.10,2449.85
3,5003,2025-12-08,SP,Marketplace,Periféricos,Teclado Mecânico,7,399.84,2798.88,1356.67
4,5004,2025-01-04,GO,Marketplace,Telefonia,Smartphone X,4,3134.85,12539.40,3656.84

In [4]:
df.shape

(420, 10)

In [6]:
df.dtypes

pedido_id               int64
data_venda             object
uf                     object
canal_venda            object
categoria              object
produto                object
quantidade_pedidos      int64
preco_unitario        float64
receita               float64
lucro                 float64
dtype: object

In [8]:
df['data_venda']

0      2025-02-14
1      2025-02-17
2      2025-07-22
3      2025-12-08
4      2025-01-04
          ...
415    2025-02-23
416    2025-12-03
417    2025-04-28
418    2025-06-07
419    2025-06-11
Name: data_venda, Length: 420, dtype: object

In [9]:
df['data_venda'] = pd.to_datetime(df['data_venda'])

In [10]:
df['data_venda']

0     2025-02-14
1     2025-02-17
2     2025-07-22
3     2025-12-08
4     2025-01-04
         ...
415   2025-02-23
416   2025-12-03
417   2025-04-28
418   2025-06-07
419   2025-06-11
Name: data_venda, Length: 420, dtype: datetime64[ns]

## 3. Perguntas antes do código

A aula enfatiza que a maior armadilha é começar com `groupby()` sem saber o que se quer responder. fileciteturn5file0

### Tarefa
Antes de programar, escreva em markdown respostas curtas para estas perguntas:

1. Qual canal de venda é o mais eficiente?
  **R: O canal mais eficiente é o de Marketplace pois tem o maior lucro.**
2. Qual categoria parece mais rentável?
  **R: A mais rentável é a de telefonia seguido (quase empatado) por informática.**
3. Quais produtos são os campeões por lucro?
  **R: Os campeões são Notebook Pro, Smartfone X e Tablet Plus (Do maior para o menor)**
4. O negócio está crescendo ao longo do tempo?
  **R: Sim, a receita no fim do ano está maior e mostra sazonalidade.**
5. Quais KPIs globais resumem melhor a operação?
  **R: Receita total, Custo total, Lucro total e Margem de Lucro.**


Depois disso, avance para o código.

## 4. KPIs globais da operação

Com base nas “4 Métricas de Ouro do Varejo” apresentadas na aula, calcule os seguintes KPIs globais da base inteira: fileciteturn5file0

- **Receita Total**
- **Lucro Total**
- **Margem de Lucro (%)**
- **Ticket Médio**

### Orientação
- Pense primeiro na fórmula de cada KPI
- Escreva os cálculos em células separadas ou em uma pequena tabela-resumo
- Se quiser, formate os resultados para facilitar a leitura

In [11]:
receita_total = df['receita'].sum()
receita_total

np.float64(1921492.22)

In [13]:
lucro_total = df['lucro'].sum()

In [14]:
margem = lucro_total / receita_total

In [15]:
ticket_medio = df['receita'].mean()

In [16]:
resumo = pd.DataFrame({
    'KPI': ['Receita Total', 'Lucro Total', 'Margem de Lucro (%)', 'Ticket Médio'],
    'Valor': [receita_total, lucro_total, margem, ticket_medio]
})

resumo

                   KPI         Valor
0        Receita Total  1.921492e+06
1          Lucro Total  5.444962e+05
2  Margem de Lucro (%)  2.833715e-01
3         Ticket Médio  4.574981e+03

In [17]:
pd.options.display.float_format = '{:,.2f}'.format
resumo

                   KPI        Valor
0        Receita Total 1,921,492.22
1          Lucro Total   544,496.15
2  Margem de Lucro (%)         0.28
3         Ticket Médio     4,574.98

### Interpretação
Escreva 3 a 5 linhas respondendo:
- O negócio parece grande ou pequeno?
  **R: Grande pois a receita chega a quase 2 milhões.**
- O lucro acompanha bem a receita?
  **R: Sim, o lucro está em torno de 28%.**
- O ticket médio sugere compras de maior valor ou de menor valor?
  **R: Compras de maior valor (R$ 4.574,98)**

## 5. Métricas derivadas

A aula mostra que **somar valores não basta**.  
Precisamos criar métricas derivadas para avaliar eficiência e comportamento. fileciteturn5file0

### Tarefa
Crie, quando fizer sentido:
- uma coluna de **margem_lucro** (`lucro / receita`)
- uma lógica para **ticket_medio** da operação ou por grupo

### Reflexão
Explique:
1. Por que receita alta não significa automaticamente melhor desempenho?
  **R: Porque você pode vender muito com uma taxa de lucro muito baixa.**
2. Em que situação a margem ajuda mais do que a receita bruta?
  **R: Quando você precisa analisar a eficiência da empresa.**

In [18]:
df['margem_lucro'] = df['lucro'] / df['receita']

In [21]:
ticket_medio = df['receita'].mean()

ticket_medio

np.float64(4574.981476190476)

In [20]:
df.head()

,pedido_id,data_venda,uf,canal_venda,categoria,produto,quantidade_pedidos,preco_unitario,receita,lucro,margem_lucro
0,5000,2025-02-14,RJ,Marketplace,Periféricos,Mouse Gamer,2,237.65,475.30,239.08,0.50
1,5001,2025-02-17,PR,Online,Informática,Monitor 27,4,"1,431.79","5,727.16","1,769.48",0.31
2,5002,2025-07-22,RJ,Marketplace,Informática,Monitor 27,5,"1,446.22","7,231.10","2,449.85",0.34
3,5003,2025-12-08,SP,Marketplace,Periféricos,Teclado Mecânico,7,399.84,"2,798.88","1,356.67",0.48
4,5004,2025-01-04,GO,Marketplace,Telefonia,Smartphone X,4,"3,134.85","12,539.40","3,656.84",0.29

## 6. Fatiando a realidade: análise por dimensão

A aula mostra que um KPI isolado não decide nada.  
É preciso perguntar: **como isso varia por canal, categoria, região e tempo?** fileciteturn5file0

### Tarefa
Liste, em markdown, quais colunas do dataset representam:
- métrica
- dimensão
- tempo

## 📊 Métricas
- receita  
- lucro  

## 🧩 Dimensões
- canal  
- categoria  
- produto  

## ⏳ Tempo
- data_venda

## 7. Análise por canal

### Pergunta de negócio
**Qual canal de venda é o mais eficiente?**

### Tarefa
Crie uma tabela agregada por `canal_venda` contendo, no mínimo:
- Receita Total
- Lucro Total
- Margem Média ou Margem Calculada
- Quantidade de pedidos
- Ticket Médio

### Depois responda
1. Qual canal gera mais receita?
2. Qual canal gera maior eficiência?
3. Se você fosse gestor, priorizaria volume ou margem?

In [22]:
tabela_canal = df.groupby('canal_venda').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'canal_venda': 'count'
})

tabela_canal.columns = ['receita_total', 'lucro_total', 'qtd_pedidos']

# margem
tabela_canal['margem'] = tabela_canal['lucro_total'] / tabela_canal['receita_total']

# ticket médio
tabela_canal['ticket_medio'] = tabela_canal['receita_total'] / tabela_canal['qtd_pedidos']

tabela_canal

             receita_total  lucro_total  qtd_pedidos  margem  ticket_medio
canal_venda
Loja Física     640,797.06   174,583.16          143    0.27      4,481.10
Marketplace     657,802.09   185,802.57          141    0.28      4,665.26
Online          622,893.07   184,110.42          136    0.30      4,580.10

1. Qual canal gera mais receita? **R: Marketplace**
2. Qual canal gera maior eficiência? **R: Marketplace (melhor margem também)**
3. Você priorizaria volume ou margem? **R: Volume pois a marrgem da loja física está bem proxima do marketplace.**

### Insight obrigatório
Escreva 1 ou 2 frases interpretando sua tabela, no estilo executivo:
- não apenas “o Online foi maior”
- mas o que isso **significa para a decisão**

**O canal Marketplace lidera tanto em receita quanto em eficiência, sendo o principal responsável pelo desempenho do negócio. Como a margem da loja física é próxima, priorizar volume (escala) faz mais sentido, focando nos canais que geram maior receita.**

## 8. Análise por categoria

### Pergunta de negócio
**Qual categoria é mais lucrativa e qual parece mais eficiente?**

### Tarefa
Crie uma tabela agregada por `categoria` com:
- Receita Total
- Lucro Total
- Margem
- Ticket Médio

### Depois responda
1. A categoria de maior receita também é a de maior margem?
2. Existe alguma categoria que parece vender bem, mas ser pouco eficiente?

In [23]:
tabela_categoria = df.groupby('categoria').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'categoria': 'count'
})

tabela_categoria.columns = ['receita_total', 'lucro_total', 'qtd_pedidos']

# margem
tabela_categoria['margem'] = tabela_categoria['lucro_total'] / tabela_categoria['receita_total']

# ticket médio
tabela_categoria['ticket_medio'] = tabela_categoria['receita_total'] / tabela_categoria['qtd_pedidos']

tabela_categoria

             receita_total  lucro_total  qtd_pedidos  margem  ticket_medio
categoria
Informática     805,376.44   219,090.15           93    0.27      8,659.96
Periféricos     116,923.08    50,424.40          107    0.43      1,092.74
Telefonia       866,292.45   219,975.58          109    0.25      7,947.64
Áudio           132,900.25    55,006.02          111    0.41      1,197.30

1. A categoria de maior receita também é a de maior margem? **R: Não.**
2. Existe categoria que vende bem mas é pouco eficiente? **R: Sim, Informática e Telefonia.**

## 9. Análise por região (UF)

### Pergunta de negócio
**Quais UFs concentram a operação?**

### Tarefa
Monte uma tabela por `uf` com:
- Receita Total
- Lucro Total
- Participação percentual da receita
- Ticket Médio

### Depois responda
1. Quais UFs concentram maior receita?
2. Existe concentração regional?
3. Se fosse necessário expandir ou reforçar logística, por onde você começaria?

In [24]:
tabela_uf = df.groupby('uf').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'uf': 'count'
})

tabela_uf.columns = ['receita_total', 'lucro_total', 'qtd_pedidos']

# participação da receita
tabela_uf['participacao'] = tabela_uf['receita_total'] / tabela_uf['receita_total'].sum()

# ticket médio
tabela_uf['ticket_medio'] = tabela_uf['receita_total'] / tabela_uf['qtd_pedidos']

tabela_uf

    receita_total  lucro_total  qtd_pedidos  participacao  ticket_medio
uf
BA     157,082.99    42,117.30           42          0.08      3,740.07
ES     181,113.70    49,838.07           39          0.09      4,643.94
GO     142,428.02    42,028.11           36          0.07      3,956.33
MG     207,614.69    61,122.25           44          0.11      4,718.52
PE     208,457.44    58,183.95           55          0.11      3,790.14
PR     174,136.19    46,155.64           35          0.09      4,975.32
RJ     218,631.91    63,960.39           38          0.11      5,753.47
RS     187,048.31    49,795.96           43          0.10      4,349.96
SC     198,143.47    60,272.32           40          0.10      4,953.59
SP     246,835.50    71,022.16           48          0.13      5,142.41

1. Quais UFs concentram maior receita? **R: SP e RJ.**
2. Existe concentração regional? **R: Não, está bem distribuído.**
3. Onde começar expansão/logística? **R: Pelas UFs que tem maior receita para que se tenha um retorno mais rápido e entao para as UFs que tem menor receita para buscar uma oportunidade de mercado.**

## 10. O motor da análise: agregações (groupby)

Nos slides, a lógica central é:
- `receita -> sum`
- `margem -> mean` ou cálculo derivado
- `produto -> count`
fileciteturn5file0

### Tarefa
Escolha **duas dimensões diferentes** e construa tabelas agregadas mostrando que você entendeu essa lógica.

Exemplos:
- por canal
- por categoria
- por UF
- por mês

In [25]:
tabela_canal = df.groupby('canal_venda').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'margem_lucro': 'mean',
    'produto': 'count'
})

tabela_canal

               receita      lucro  margem_lucro  produto
canal_venda
Loja Física 640,797.06 174,583.16          0.34      143
Marketplace 657,802.09 185,802.57          0.35      141
Online      622,893.07 184,110.42          0.35      136

In [26]:
tabela_categoria = df.groupby('categoria').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'margem_lucro': 'mean',
    'produto': 'count'
})

tabela_categoria

               receita      lucro  margem_lucro  produto
categoria
Informática 805,376.44 219,090.15          0.29       93
Periféricos 116,923.08  50,424.40          0.43      107
Telefonia   866,292.45 219,975.58          0.25      109
Áudio       132,900.25  55,006.02          0.41      111

## 11. Campeões e vilões (Top N)

A aula destaca o poder dos rankings curtos e focados. fileciteturn5file0

### Tarefa
Crie:
- Top 10 produtos por **lucro**
- Top 10 produtos por **receita**
- 5 categorias ou UFs com **pior margem** ou pior desempenho

### Perguntas
1. Quem são os “campeões”?
2. Quem são os “vilões”?
3. Que ação tática poderia ser tomada com base nisso?

In [27]:
top_lucro = df.groupby('produto')['lucro'].sum().sort_values(ascending=False).head(10)
top_lucro

produto
Notebook Pro       153,094.84
Smartphone X       118,198.25
Tablet Plus        101,777.33
Monitor 27          65,995.31
Teclado Mecânico    33,939.07
Caixa de Som        28,316.37
Headset Pro         26,689.65
Mouse Gamer         16,485.33
Name: lucro, dtype: float64

In [28]:
top_receita = df.groupby('produto')['receita'].sum().sort_values(ascending=False).head(10)
top_receita

produto
Notebook Pro       594,132.74
Smartphone X       489,572.08
Tablet Plus        376,720.37
Monitor 27         211,243.70
Teclado Mecânico    79,973.75
Caixa de Som        68,956.76
Headset Pro         63,943.49
Mouse Gamer         36,949.33
Name: receita, dtype: float64

In [29]:
pior_categoria = df.groupby('categoria').agg({
    'receita': 'sum',
    'lucro': 'sum'
})

pior_categoria['margem'] = pior_categoria['lucro'] / pior_categoria['receita']

pior_categoria.sort_values('margem').head(5)

               receita      lucro  margem
categoria
Telefonia   866,292.45 219,975.58    0.25
Informática 805,376.44 219,090.15    0.27
Áudio       132,900.25  55,006.02    0.41
Periféricos 116,923.08  50,424.40    0.43

1. Quem são os “campeões”? **R: Notebook Pro, Smartfone X e Tablet Plus.**
2. Quem são os “vilões”? **R: Mouse Gamer, Headset Pró e Caixa de Som.**
3. Que ação tática poderia ser tomada com base nisso? **R: Poderia aumentar o investimento nos campeões e revisar os vilões (preço, custo ou estratégia).**

## 12. Análise temporal

A aula reforça que sem tempo a análise fica estática. fileciteturn5file0

### Tarefa
1. Converta `data_venda` para data, se necessário
2. Crie colunas auxiliares como:
   - mês
   - trimestre (opcional)
3. Gere uma tabela agregada por mês com:
   - receita
   - lucro
   - ticket médio ou margem

### Depois responda
1. O lucro parece crescer ao longo do tempo?
2. O último trimestre foi melhor que o anterior?
3. Quais meses concentram as vendas de fim de ano?

In [30]:
df['data_venda'] = pd.to_datetime(df['data_venda'])

In [31]:
df['mes'] = df['data_venda'].dt.month
df['trimestre'] = df['data_venda'].dt.quarter

In [33]:
tabela_mes = df.groupby('mes').agg({
    'receita': ['sum', 'mean'],
    'lucro': 'sum'
})

tabela_mes.columns = ['receita_total', 'ticket_medio', 'lucro_total']

tabela_mes

     receita_total  ticket_medio  lucro_total
mes
1       161,571.89      4,251.89    46,515.14
2       108,587.03      3,502.81    29,998.87
3        87,902.22      3,516.09    23,923.66
4       148,930.46      3,463.50    43,094.00
5       106,355.17      4,624.14    30,334.32
6       134,685.83      4,081.39    38,592.70
7       196,651.96      5,959.15    57,913.44
8       160,240.62      4,330.83    45,881.36
9       109,291.03      3,311.85    31,938.44
10      158,226.19      4,653.71    41,463.02
11      325,537.31      7,398.58    87,763.18
12      223,512.51      4,858.97    67,078.02

1. O lucro parece crescer ao longo do tempo? **R: Sim, principalmente no meio e no final do ano.**
2. O último trimestre foi melhor que o anterior? **R: Sim, o ultimo trimestre teve o melhor resultado.**
3. Quais meses concentram as vendas de fim de ano? **R: Novembro e Dezembro (certamente por conta do natal e outras promoções como black friday ou novos lançamentos).**

## 13. Fluxo de investigação do analista

A aula apresenta a sequência:
**Pergunta -> Colunas necessárias -> Tipo de resposta/gráfico**. fileciteturn5file0

### Tarefa
Preencha, em markdown, pelo menos 3 exemplos no formato:

- **Pergunta de negócio:** ...
- **Colunas necessárias:** ...
- **Métrica/KPI:** ...
- **Tipo de resposta esperada:** tabela, ranking, tendência etc.

## Exemplo 1
Pergunta de negócio: Qual canal de venda é o mais eficiente?  
Colunas necessárias: canal_venda, receita, lucro  
Métrica/KPI: receita total, lucro total, margem  
Tipo de resposta esperada: tabela agregada  

## Exemplo 2
Pergunta de negócio: Quais produtos são os mais lucrativos?  
Colunas necessárias: produto, lucro  
Métrica/KPI: lucro total  
Tipo de resposta esperada: ranking (Top N)  

## Exemplo 3
Pergunta de negócio: O negócio está crescendo ao longo do tempo?  
Colunas necessárias: data_venda, receita, lucro  
Métrica/KPI: receita total e lucro por mês  
Tipo de resposta esperada: tendência (série temporal)

## 14. O insight exige palavras

Segundo a aula, o mercado valoriza quem comunica decisões, não apenas quem roda código. fileciteturn5file0

### Tarefa
Escolha **duas tabelas agregadas** que você criou e escreva, para cada uma, **1 ou 2 frases de interpretação executiva**.

Exemplo de estilo:
- “O canal X concentra maior volume de receita, mas o canal Y apresenta margem superior.”
- “Recomenda-se revisar custos/expansão/priorização com base nesse resultado.”

## Análise por canal
O canal Marketplace concentra o maior volume de receita e também apresenta a melhor margem, sendo o principal motor de crescimento do negócio.  
Recomenda-se priorizar investimentos nesse canal para maximizar escala e rentabilidade.

## Análise por categoria
Algumas categorias apresentam alto volume de vendas, mas com margens inferiores, indicando menor eficiência operacional.  
Recomenda-se revisar preços ou custos nessas categorias para melhorar a rentabilidade.

## 15. Case Varejo Brasil — Entrega final

A aula propõe quatro entregas centrais para o gestor. fileciteturn5file0

### Sua missão final
Organize o notebook para entregar:

1. **KPIs Globais**
2. **Tabelas por Dimensões Críticas**
   - por canal
   - por categoria
3. **Top 10 Produtos por Lucro**
4. **Conclusão final com pelo menos uma decisão tática**

### Importante
A conclusão final deve ser escrita em linguagem clara, direta e orientada à decisão.

In [34]:
receita_total = df['receita'].sum()
lucro_total = df['lucro'].sum()
margem = lucro_total / receita_total
ticket_medio = df['receita'].mean()

kpis = pd.DataFrame({
    'KPI': ['Receita Total', 'Lucro Total', 'Margem (%)', 'Ticket Médio'],
    'Valor': [receita_total, lucro_total, margem, ticket_medio]
})

kpis

             KPI        Valor
0  Receita Total 1,921,492.22
1    Lucro Total   544,496.15
2     Margem (%)         0.28
3   Ticket Médio     4,574.98

In [35]:
tabela_canal = df.groupby('canal_venda').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'canal_venda': 'count'
})

tabela_canal.columns = ['receita_total', 'lucro_total', 'qtd_pedidos']

tabela_canal['margem'] = tabela_canal['lucro_total'] / tabela_canal['receita_total']
tabela_canal['ticket_medio'] = tabela_canal['receita_total'] / tabela_canal['qtd_pedidos']

tabela_canal

             receita_total  lucro_total  qtd_pedidos  margem  ticket_medio
canal_venda
Loja Física     640,797.06   174,583.16          143    0.27      4,481.10
Marketplace     657,802.09   185,802.57          141    0.28      4,665.26
Online          622,893.07   184,110.42          136    0.30      4,580.10

In [36]:
tabela_categoria = df.groupby('categoria').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'categoria': 'count'
})

tabela_categoria.columns = ['receita_total', 'lucro_total', 'qtd_pedidos']

tabela_categoria['margem'] = tabela_categoria['lucro_total'] / tabela_categoria['receita_total']
tabela_categoria['ticket_medio'] = tabela_categoria['receita_total'] / tabela_categoria['qtd_pedidos']

tabela_categoria

             receita_total  lucro_total  qtd_pedidos  margem  ticket_medio
categoria
Informática     805,376.44   219,090.15           93    0.27      8,659.96
Periféricos     116,923.08    50,424.40          107    0.43      1,092.74
Telefonia       866,292.45   219,975.58          109    0.25      7,947.64
Áudio           132,900.25    55,006.02          111    0.41      1,197.30

In [37]:
top_produtos = df.groupby('produto')['lucro'].sum().sort_values(ascending=False).head(10)
top_produtos

produto
Notebook Pro       153,094.84
Smartphone X       118,198.25
Tablet Plus        101,777.33
Monitor 27          65,995.31
Teclado Mecânico    33,939.07
Caixa de Som        28,316.37
Headset Pro         26,689.65
Mouse Gamer         16,485.33
Name: lucro, dtype: float64

## Conclusão

O canal Marketplace se destaca como principal fonte de receita e também apresenta a melhor eficiência, sendo o principal motor do negócio.  
Além disso, os produtos com maior lucro indicam concentração de resultado em itens específicos, reforçando a importância de gestão de portfólio.

Como decisão tática, recomenda-se priorizar o canal Marketplace e aumentar o investimento nos produtos mais lucrativos, além de revisar categorias com menor margem para melhorar a rentabilidade geral.

## 16. Desafio extra (opcional)

Monte uma pequena tabela executiva final com:
- Receita Total
- Lucro Total
- Margem
- Ticket Médio

e depois crie uma segunda tabela por canal com os mesmos indicadores.

Compare os resultados e explique:
- o KPI global esconde alguma diferença importante entre os canais?

In [38]:
receita_total = df['receita'].sum()
lucro_total = df['lucro'].sum()
margem = lucro_total / receita_total
ticket_medio = df['receita'].mean()

tabela_global = pd.DataFrame({
    'Receita Total': [receita_total],
    'Lucro Total': [lucro_total],
    'Margem': [margem],
    'Ticket Médio': [ticket_medio]
})

tabela_global

   Receita Total  Lucro Total  Margem  Ticket Médio
0   1,921,492.22   544,496.15    0.28      4,574.98

In [39]:
tabela_canal = df.groupby('canal_venda').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'canal_venda': 'count'
})

tabela_canal.columns = ['receita_total', 'lucro_total', 'qtd_pedidos']

tabela_canal['margem'] = tabela_canal['lucro_total'] / tabela_canal['receita_total']
tabela_canal['ticket_medio'] = tabela_canal['receita_total'] / tabela_canal['qtd_pedidos']

tabela_canal

             receita_total  lucro_total  qtd_pedidos  margem  ticket_medio
canal_venda
Loja Física     640,797.06   174,583.16          143    0.27      4,481.10
Marketplace     657,802.09   185,802.57          141    0.28      4,665.26
Online          622,893.07   184,110.42          136    0.30      4,580.10

## 17. Entrega esperada

Seu notebook deve demonstrar:
- organização
- fórmulas corretas de KPI
- uso adequado de `groupby`, `agg`, `sort_values`
- leitura temporal coerente
- interpretação escrita dos resultados

### Mensagem principal da aula
Transformar linhas de dados limpos em **apoio real para decisões de negócio**. fileciteturn5file0